---
title: "01_exercice"
author: "jorge_callejo"
date: "2022-11-06"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
theme_set(theme_light())
```


```{r}
data <- read_csv("database/data.csv")
```


```{r}
data %>% 
  view()
#base de datos referente a una encuentas de los mejores profesiones pagadas para hombres y mujeres
```

```{r}
# NOTA: recomendación revisar la tabla con la que se trabajara para entender que información contiene, se recomienda empezar escogiendo un par de columnas y ver que resultados arroja
dim(data)
```
```{r}
str(data)
```

### what common category?

```{r}
data %>% 
  count(Major_category,
        wt = Total,
        sort = TRUE
        ) %>% 
  mutate(Major_category = fct_reorder(Major_category, n)) %>%   ggplot(aes(
    x = Major_category,
    y = n,
    fill = Major_category
  ))+
  geom_col()+
  coord_flip()+
  scale_y_continuous(labels = comma_format())+
  labs(
    x = "",
    y = "Total # de graduados"
    
  )+
  theme(legend.position = "none")
  
  
```
```{r}
data %>% 
mutate(
  Major = str_to_title(Major),
  Major = fct_reorder(Major, Total)
) %>% 
  arrange(desc(Total)) %>% 
  head(20) %>% 
  ggplot(aes(
    x = Major,
    y = Total,
    fill = Major_category
  ))+
  geom_col()+
  coord_flip()+
  scale_y_continuous(labels = comma_format())+
  labs(
    x = "",
    y = "Total # de graduados"
  )+
  theme(legend.position = "bottom")
```


### what categories of major make more money than others?

```{r}
#Distribución de la mediana 
data %>% 
  ggplot(aes(
    x = Median
  ))+
  geom_histogram()
```
```{r}
data %>% 
  ggplot(aes(
    x = Major_category,
    y = Median
  ))+
  geom_boxplot()+
  coord_flip()
```
```{r}
data %>% 
  dplyr::mutate(Major_category = fct_reorder(Major_category, Median)) %>% 
  ggplot(aes(
    x = Major_category,
    y = Median
  ))+
  geom_boxplot()+
  scale_y_continuous(labels = dollar_format())+
  coord_flip()
```
```{r}
data %>% 
  dplyr::mutate(Major_category = fct_reorder(Major_category, Median)) %>% 
  ggplot(aes(
    x = Major_category,
    y = Median,
    fill = Major_category
  ))+
  geom_boxplot()+
  scale_y_continuous(labels = dollar_format())+
  expand_limits(y = 0)+
  coord_flip()+
  theme(legend.position = "none")
```

```{r}
#install.packages("plotly")
library(plotly)

g <- data %>% 
  mutate(Major_category = fct_lump(Major_category, 4)) %>%   ggplot(aes(
    x  = ShareWomen,
    y =  Median,
    color = Major_category,
    size = Sample_size,
    label = Major
  ))+
  geom_point()+
  geom_smooth(aes(group = 1), method = "lm")+
  scale_x_continuous(labels = percent_format())+
  scale_y_continuous(labels = dollar_format())+
  expand_limits(y = 0)

ggplotly(g)
```




```{r}
data %>% 
  dplyr::group_by(Major_category) %>% 
  dplyr::summarise(Median = median(Median)) %>% 
  dplyr::mutate(Major_category = fct_reorder(Major_category, Median)) %>% 
  ggplot(aes(
    x = Major_category,
    y = Median
  ))+
  geom_col()+
  scale_y_continuous(labels = dollar_format())+
  coord_flip()
```
###  what are the heghest earnig majors?
```{r}
data %>% 
  arrange(desc(Median)) %>% 
  select(Major, Major_category, Median, P25th, P75th) %>% 
  view()
```

```{r}
data %>% 
  arrange(desc(Median)) %>% 
  select(Major, Major_category, Median, P25th, P75th) %>% 
  head(20) %>% 
  mutate(Major = fct_reorder(Major, Median)) %>% 
  ggplot(aes(
    x = Major,
    y = Median,
    color = Major_category
  ))+
  geom_point()+
  scale_y_continuous(labels = dollar_format())+
  expand_limits(y = 0)+
  coord_flip()
```
```{r}
base <- data %>%
    na.omit(data) %>% 
  arrange(desc(Median)) %>% 
  select(Major, Major_category, Median, P25th, P75th, Sample_size, Men, Women) %>%
  mutate(
    Major = str_to_title(Major),
    Major = fct_reorder(Major, Median)
    )
```


```{r}
  base %>% 
  head(20) %>% 
  ggplot(aes(
    x = Major,
    y = Median,
    color = Major_category
  ))+  
  geom_point()+
  geom_errorbar(aes(
    ymin = P25th,
    ymax = P75th
  ))+
  scale_y_continuous(labels = dollar_format())+
  coord_flip()
```
```{r}
base %>% 
  head(20) %>% 
  ggplot(aes(
    x = Major,
    y = Median,
    color = Major_category
  ))+
  geom_point()+
  geom_errorbar(aes(
    ymin = P25th,
    ymax = P75th
  ))+
  scale_y_continuous(labels = dollar_format())+
  expand_limits(y = 0)+
  coord_flip()
```

```{r}
base %>% 
  filter(Sample_size >= 100) %>% 
  head(20) %>% 
  ggplot(aes(
    x  = Major,
    y =  Median,
    color = Major_category
  ))+
  geom_point()+
  geom_errorbar(aes(
    ymin = P25th,
    ymax = P75th
  ))+
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format())+
  coord_flip()+
  labs(
    title = "¿En qué área se especializan los mayores ingresos?",
    subtitle = "Top 20 Mayores carreras con al menos 100 graduados encuestados con una variación desde el 1er cuartil al 3er cuartil",
    y = "Media de los salarios de graduados",
    x = "Especialidad Universitaria"
  )


```

### what are the lowest earning majors?

```{r}
base %>% 
    tail(20) %>% 
  ggplot(aes(
    x = Major,
    y = Median,
    color = Major_category
  ))+
  geom_point()+
  geom_errorbar(aes(
    ymin = P25th,
    ymax = P75th
  ))+
  scale_y_continuous(labels = dollar_format())+
  expand_limits(y = 0)+
  coord_flip()
```

```{r}
base %>% 
  ggplot(aes(
    x = Sample_size,
    y = Median
  ))+
  geom_point()
```
```{r}
base %>% 
  ggplot(aes(
    x = Sample_size,
    y = Median
  ))+
  geom_point()+
  scale_x_log10()
```
```{r}
base %>% 
  ggplot(aes(
    x = Sample_size,
    y = Median
  ))+
  geom_point()+
  geom_text(aes(
    label = Major
  ),
  check_overlap = TRUE)+
  scale_x_log10()
```
```{r}
base %>% 
  ggplot(aes(
    x = Sample_size,
    y = Median
  ))+
  geom_point()+
  geom_text(aes(
    label = Major
  ),
  check_overlap = TRUE,
  vjust = 1,
  hjust = 1
  )+
  scale_x_log10()
```
```{r}
base %>% 
  filter(Sample_size >= 100) %>% 
  tail(20) %>% 
  ggplot(aes(
    x  = Major,
    y =  Median,
    color = Major_category
  ))+
  geom_point()+
  geom_errorbar(aes(
    ymin = P25th,
    ymax = P75th
  ))+
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format())+
  coord_flip()+
  labs(
    title = "¿En qué área se especializan los mayores ingresos?",
    subtitle = "Top 20 carreras menor pagadas con al menos 100 graduados encuestados con una variación desde el 1er cuartil al 3er cuartil",
    y = "Media de los salarios de graduados",
    x = "Especialidad Universitaria"
  )

```
###  how does gender breakdown relate to typical earnings?

```{r}
data %>% 
  arrange(desc(Total)) %>% 
  head(20) %>% 
  mutate(
    Major = str_to_title(Major),
    Major = fct_reorder(Major, Total)
    ) %>% 
  gather(Gender, Number, Men, Women) %>% 
  select(Major, Gender, Number) %>% 
  ggplot(aes(
    x = Major,
    y = Number,
    fill = Gender
  ))+
  geom_col()+
  coord_flip()+
  scale_y_continuous(labels = comma_format())
  
```

```{r}
data %>% 
  na.omit(data$Total) %>% 
  mutate(
    Major_category = str_to_title(Major_category),
    Major_category = fct_reorder(Major_category, Total)
    ) %>% 
  gather(Gender, Number, Men, Women) %>% 
  ggplot(aes(
    x = Major_category,
    y = Total, 
    fill = Gender
  ))+
  geom_col()+
  coord_flip()+
  labs(
    x = "",
    y = "Total de Graduados por Genero"
  )
```


```{r by_major_category}
by_major_categoy <-data %>% 
  na.omit(data$Total) %>% 
  group_by(Major_category) %>% 
  summarise(
    Men = sum(Men),
    Women = sum(Women),
    Total = sum(Total),
    MedianSalary = sum(Median * Sample_size) / sum(Sample_size)
  ) %>%
  mutate(
    ShareWomen = round(Women/Total,2),
    ) 
```

```{r}
#install.packages("ggrepel")
library(ggrepel)

by_major_categoy %>% 
  ggplot(aes(
    x = ShareWomen,
    y = MedianSalary
  ))+
  geom_point()+
  geom_smooth(method = "lm")+
  geom_text_repel(aes(
    label = Major_category
  ),
  force = .1
  )+
  expand_limits(y = 0)
```
```{r}
data %>% 
  ggplot(aes(
    x = ShareWomen,
    y = Median,
    color = Major_category
  ))+
  geom_point()+
  geom_smooth(aes(
    group = 1
  ),
    method = "lm")+
  expand_limits(y = 0)
```


```{r}
data %>% 
  select(Major, Total, ShareWomen, Sample_size, Median) %>% 
  lm(Median ~ ShareWomen, data=., weights = Sample_size) %>%   summary()
```
```{r}
data %>% 
  filter(Sample_size >= 100) %>% 
  mutate(IQR = P75th - P25th) %>% 
  arrange(desc(IQR)) %>% 
  view()
```


































































