---
title: "14_exercice"
author: "jorge_callejo"
date: "2022-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(scales)
library(countrycode)
library(ggplot2)
theme_set(theme_minimal())
```

```{r}
milk_product_fact <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milk_products_facts.csv") 
```

```{r}
milk_product_tidied <- milk_product_fact %>% 
  gather(product, lbs_per_person, -year) %>% 
  separate(product, c("category", "product"), 
           sep = "_",
           extra = "merge",
           fill = "right") %>% 
  mutate(product = coalesce(product, category),
         product = str_to_title(str_replace_all(product, "_", " ")),
         category = str_to_title(category),
         product = ifelse(product == "Other", paste(product, category), product)) 
```

```{r}
milk_product_tidied %>% 
  group_by(category, year) %>% 
  view()
```


```{r}
milk_product_tidied %>% 
  filter(year == max(year)) %>% 
  mutate(
    product = str_to_title(str_replace_all(product, "_", " ")), 
    product = fct_reorder(product, lbs_per_person, sum)) %>% 
  ggplot(aes(
    product,
    lbs_per_person,
    fill = product
  ))+
  geom_col(show.legend = FALSE)+
  coord_flip()+
  labs(x = "",
       y = "Pounds consumend per US Person in 2017")
  
```
```{r}
milk_product_tidied %>% 
  filter(year == max(year)) %>% 
  mutate(
    product = str_to_title(str_replace_all(product, "_", " ")), 
    product = fct_reorder(product, lbs_per_person, sum)) %>% 
  ggplot(aes(
    product,
    lbs_per_person,
    fill = category
  ))+
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "Pounds consumend per US Person in 2017")+
  theme(legend.position = "bottom")
  
```

```{r}
milk_product_tidied %>% 
  group_by(category, year) %>% 
  summarise(lbs_per_person = sum(lbs_per_person)) %>% 
  ggplot(aes(
    year,
    lbs_per_person,
    color = category
  ))+
  geom_line()+
  labs(title = "Dairy consumption by category",
       subtitle = "Based in US consuption (source:USDA)",
       x =  "year",
       y = "lbs per person")
```

```{r}
milk_product_tidied %>% 
  group_by(product = fct_lump(product, 6, w = lbs_per_person),
           year) %>% 
  summarise(lbs_per_person = sum(lbs_per_person)) %>% 
  ggplot(aes(
    year,
    lbs_per_person,
    color=product
  ))+
  geom_line()

```
```{r}
milk_product_tidied %>% 
  filter(product != "Milk") %>% 
  group_by(product = fct_lump(product, 6, w = lbs_per_person),
           year) %>% 
  summarise(lbs_per_person = sum(lbs_per_person)) %>% 
  ggplot(aes(
    year,
    lbs_per_person,
    color=product
  ))+
  geom_line(size = 1)

```
```{r}
milk_product_tidied %>% 
  ggplot(aes(
    year,
    lbs_per_person,
    color = product
  ))+
  geom_line(show.legend = FALSE)+
  facet_wrap(~product, scales = "free")+
  expand_limits(y = 0)
```
```{r}
#series de tiempos
#https://business-science.github.io/sweep/

# install.packages("forecast")
# install.packages("devtools")
# devtools::install_github("business-science/sweep")

# REALIZAR PRUEBAS EN LA PAGINA OFICIAL 

library(forecast)
library(broom)

library(sweep)
library(timetk)
library(dplyr)
library(purrr)
library(survey)

milk_product_ts <-  milk_product_tidied %>%
  mutate(year = as.Date("0001-01-01") + years(year)-1) %>%
  nest(-category, -product) %>%
  mutate(ts = map(data, tk_ts, start = 1975, freq = 1))


milk_product_ts %>%
  crossing(model_name = c("auto.arima", "ets")) %>% 
  mutate(model = map2(model_name, ts, ~ invoke(.x, list(.y))),
         forecast = map(model, forecast, h = 10)) %>% 
  unnest(map(forecast, sw_sweep)) %>% 
  view()

%>%
  ggplot(aes(
    index,
        lbs_per_person,
    color = model_name, lty = key
  ))+
  geom_line()+
  geom_ribbon(aes(
    ymin = lo.80,
    ymax = hi.80,
    alpha = .5
  ))+
  facet_wrap(~ product, scales = "free_y")+
  expand_limits(y = 0)+
  scale_x_continuous(breaks = c(1980,2000,2020))+
  scale_linetype_discrete(guide = FALSE)+
  labs(x = "year")

```

