---
title: "16_exercice"
author: "jorge_callejo"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(countrycode)
library(ggplot2)
library(plotly)
theme_set(theme_minimal())
```


```{r, echo=FALSE}
jobs_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv")
earnings_female <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv") 
employed_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv") 
```

```{r, echo=FALSE}
summarize_jobs_gender <- function(tbl) {
  tbl %>% 
    summarise(total_earnings = sum(total_earnings * total_workers) / sum(total_workers),
              total_earnings_male = sum(total_earnings_male * total_workers, na.rm = TRUE) / sum(workers_male[!is.na(total_earnings_male)]),
              total_earnings_female = sum(total_earnings_female * workers_female, na.rm = TRUE)/ sum(workers_female[!is.na(total_earnings_female)]),
              total_workers = sum(total_workers),
              workers_male = sum(workers_male),
              workers_female = sum(workers_female)) %>% 
    mutate(wage_percent_of_male =  total_earnings_female / total_earnings_male)
}
```

```{r, echo=FALSE}
by_year_major_category <-jobs_gender %>% 
  filter(complete.cases(.)) %>% 
  group_by(year, major_category) %>% 
  summarize_jobs_gender()
```


```{r}
 by_year_major_category%>% 
  mutate(major_category = fct_reorder(major_category,  -total_earnings)) %>% 
  ggplot(aes(
    year,
    total_earnings,
    color = major_category
  ))+
  geom_line()+
  expand_limits(y = 0)
```
```{r}
 by_year_major_category%>% 
  mutate(major_category = fct_reorder(major_category,  -wage_percent_of_male)) %>% 
  ggplot(aes(
    year,
    wage_percent_of_male,
    color = major_category
  ))+
  geom_line()+
  scale_y_continuous(labels = scales::percent_format())
```
```{r, echo=FALSE}
by_minor_category_2016 <- jobs_gender %>% 
  filter(year == 2016) %>% 
  group_by(major_category, minor_category) %>% 
  summarize_jobs_gender() %>% 
  ungroup() 
```
```{r}
by_minor_category_2016 %>% 
  mutate(minor_category = fct_reorder(minor_category, wage_percent_of_male)) %>% 
  ggplot(aes(
    minor_category,
    wage_percent_of_male,
    fill = major_category
  ))+
  geom_col()+
  coord_flip()
```

```{r}
by_minor_category_2016 %>% 
  mutate(minor_category = fct_reorder(minor_category, wage_percent_of_male)) %>% 
  ggplot(aes(
    minor_category,
    wage_percent_of_male,
    fill = major_category
  ))+
  geom_col(show.legend = FALSE)+
  facet_wrap(~major_category, scales = "free_y")+
  coord_flip()
```

```{r}
plotly_graph <-jobs_gender %>% 
  filter(year == "2016", major_category == "Healthcare Practitioners and Technical") %>% 
  arrange(desc(wage_percent_of_male)) %>% 
  ggplot(aes(
    workers_female / total_workers,
    total_earnings_female / total_earnings_male,
    label = occupation,
    size = total_workers
  ))+
  geom_point(show.legend = FALSE)+
  scale_color_gradient2(low = "red", high = "blue", midpoint = .85, mid = "yellow")+
  scale_size_continuous(range = c(1,10))+
  theme(legend.position = "bottom")+
  labs(
    x = "total # of workers",
    y = " % of workforce reported as female",
    color = "% of median salary female"
  )
ggplotly(plotly_graph)

```

```{r}
plotly_graph_1 <-jobs_gender %>% 
  filter(year == "2016", major_category == "Computer, Engineering, and Science", total_workers > 20000) %>% 
  arrange(desc(wage_percent_of_male)) %>% 
  ggplot(aes(
    workers_female / total_workers,
    total_earnings_female / total_earnings_male,
    color = minor_category,
    label = occupation,
    size = total_workers
  ))+
  geom_point(show.legend = FALSE)+
  scale_size_continuous(range = c(1,10))+
  labs(
    x = " % of workforce reported as female",
    y = " % of median salary female"
  )+
  scale_x_continuous(labels = scales::percent_format())+
  scale_y_continuous(labels = scales::percent_format())+
  theme(legend.position = "bottom")

ggplotly(plotly_graph_1)
```

```{r}
# file | new flie | web shiny app
```

