---
title: "20_exercice"
author: "jorge_callejo"
date: "2022-12-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(countrycode)
library(ggplot2)
library(plotly)
theme_set(theme_minimal())
```


```{r, data, include=FALSE}
player_dob <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-09/player_dob.csv")
```

```{r}
grand_slams <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-09/grand_slams.csv") %>% 
arrange(year, grand_slam, name, gender) %>% 
distinct(year, grand_slam, name, .keep_all = TRUE) %>% 
               mutate(grand_slam = str_replace(str_to_title(str_replace(grand_slam, "_", " ")), "Us", "US")) 
```


```{r}
grand_slam_timeline <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-09/grand_slam_timeline.csv")

age_slams_comb <- left_join(grand_slams, player_dob, by = c("name")) %>% 
  mutate(age = tournament_date - date_of_birth) %>% # needs to be datetime
  group_by(name, age, gender) %>%
  summarize(counts = n()) %>% 
  group_by(name) %>% 
  mutate(total_wins = cumsum(counts)) %>% 
  arrange(desc(total_wins))
```




```{r}
grand_slams %>% 
  count(name, gender, sort = TRUE) %>% 
  head(16) %>% 
  mutate(name = fct_reorder(name, n)) %>% 
  ggplot(aes(
    name,
    n
  ))+
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "# og gran slam tournament won",
       title = "tenis players with the most grand slam tournament wins",
       subtitle = "1968 - Present")
```
```{r}
grand_slams %>% 
  count(name, gender, grand_slam, sort = TRUE) %>% 
  head(16) %>% 
  mutate(name = fct_reorder(name, n)) %>% 
  ggplot(aes(
    name,
    n,
    fill = grand_slam
  ))+
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "# of Gran Slam tournament won",
       title = "tenis players with the most grand slam tournament wins",
       subtitle = "1968 - Present")+
  theme(legend.position = "bottom")
```


```{r}
grand_slams %>% 
  count(name, gender, sort = TRUE) %>% 
  head(16) %>% 
  mutate(name = fct_reorder(name, n)) %>% 
  ggplot(aes(
    name,
    n
  ))+
  geom_col()+
  coord_flip()+
  facet_wrap(~gender, scales = "free", ncol = 1)
```
```{r}
# var = c("#ffffcc", "#fed976", "#fd8d3c", "#e31a1c")
grand_slams %>% 
  count(name, gender, grand_slam, sort = TRUE) %>% 
  add_count(name, wt = n) %>% 
  filter(nn >= 8) %>% 
   mutate(name = fct_reorder(name, n, sum)) %>% 
  ggplot(aes(
    name,
    n, 
    fill = grand_slam
  ))+
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "# of Gran Slam tournament won",
       title = "tenis players with the most grand slam tournament wins",
       subtitle = "1968 - Present")+
  theme(legend.position = "bottom")

```

```{r}
grand_slams %>% 
  count(name, gender, grand_slam, sort = TRUE) %>%
  add_count(name, wt = n) %>% 
  filter(nn >= 8) %>% 
  mutate(name = fct_reorder(name, n, sum))%>% 
  ggplot(aes(
    name,
    n, 
    fill = grand_slam
  ))+
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "# of Gran Slam tournament won",
        title = "tenis players with the most grand slam tournament wins",
        subtitle = "1968 - Present")
```

```{r, echo=FALSE}
grand_slams_age <- player_dob %>% 
  select(name, date_of_birth) %>% 
  inner_join(grand_slams, by = "name") %>% 
  mutate(age = round(as.numeric(difftime(tournament_date, date_of_birth, units = "days"))/365.25,0))
```


```{r}
grand_slams_age %>% 
  ggplot(aes(
    age
  ))+
  geom_histogram(binwidth = 1)
```
la media de edad para jugar el gran slam is `r median(grand_slams_age$age)`

```{r}
grand_slams_age %>% 
  ggplot(aes(
    age,
    fill = gender
  ))+
  geom_histogram(binwidth = 1, 
                 position = "identity",
                 alpha = 0.75)
```
```{r}
grand_slams_age %>% 
  mutate(age = 10 * (year(tournament_date) %/% 10)) %>% 
  ggplot(aes(
    tournament_date,
    age,
    fill = gender,
    group = gender
  ))+
  geom_boxplot()+
  coord_flip()
```
```{r}
grand_slams_age %>% 
  mutate(decade = 10 * (year(tournament_date) %/% 10)) %>% 
  ggplot(aes(
    decade,
    age,
    fill = gender,
    group = interaction(gender, decade)
  ))+
  geom_boxplot()+
  coord_flip()
```
```{r}
by_decade_gender <- grand_slams_age %>% 
  mutate(decade = 10 * (year(tournament_date) %/% 10)) %>% 
  filter(decade >= 1970) %>% 
  group_by(decade, gender, name) %>% 
  summarise(age = mean(age),
            rolling_win_count = mean(rolling_win_count),
            wins = n()) %>% 
  summarise(age = mean(age),
            rolling_win_count = mean(rolling_win_count),
            wins = n()) 

```

```{r}
by_decade_gender %>% 
  ggplot(aes(
    decade,
    age,
    color = gender
  ))+
  geom_line()+
  labs(title = "Averange age of grand slam winners over time", 
       subtitle = "Each player was counted only once per decade")
```

## predicting the winner of a grand slam tournament

```{r}
grand_slam_timeline %>% 
  count(outcome, sort = TRUE)
```

```{r}
tournaments <- grand_slams %>% 
  select(year, tournament = grand_slam, gender, tournament_date)

```


```{r}
timeline_processed <- grand_slam_timeline %>% 
  inner_join(tournaments, by = c("year", "tournament", "gender")) %>% 
  arrange(player, tournament_date) %>% 
  filter(outcome != "Absent",
         !str_detect(outcome, "Qualif")) %>% 
  group_by(player) %>% 
  mutate(rolling_play_count = row_number()-1,
         rolling_won_count = lag(cumsum(outcome == "Won"), default = 0),
         rollin_finals_count = lag(cumsum(outcome %in% c("Won", "Finalist")), default = 0)) %>% 
  ungroup() %>% 
  filter(!(year == 1977 & tournament == "Australian Open")) %>% 
  mutate(won = outcome == "Won")
```

```{r}
timeline_processed %>% 
  filter(outcome %in% c("Finalist", "Won")) %>% 
  arrange(tournament_date) %>% 
  group_by(rolling_won_count = pmin(rolling_won_count, 10)) %>% 
  summarise(mean_won = mean(won),
            observations = n()) %>% 
  ggplot(aes(
    rolling_won_count,
    mean_won
  ))+
  geom_line()+
  expand_limits(y = 0)
```
```{r}
timeline_processed %>% 
  filter(outcome %in% c("Finalist", "Won")) %>% 
  select(year, tournament, gender, outcome, rolling_won_count) %>% 
  spread(outcome, rolling_won_count)
```

```{r}

timeline_processed %>% 
  filter(outcome %in% c("Finalist", "Won")) %>% 
  select(year, tournament, gender, outcome, rolling_won_count) %>% 
  spread(outcome, rolling_won_count) %>% 
  count(result = case_when(
    Won > Finalist ~ "Won > Finalist",
    Won == Finalist ~ "Won == Finalist",
    Won < Finalist ~ "Won < Finalist"
  )) %>% 
  mutate(n / sum(n))

```

```{r}

timeline_processed %>% 
  filter(outcome %in% c("Finalist", "Won")) %>% 
  select(year, tournament, gender, outcome, rollin_finals_count) %>% 
  spread(outcome, rollin_finals_count) %>% 
  count(result = case_when(
    Won > Finalist ~ "Won > Finalist",
    Won == Finalist ~ "Won == Finalist",
    Won < Finalist ~ "Won < Finalist"
  )) %>% 
  mutate(n / sum(n))

```

```{r}
outcome_rakings <- c("1st Round", "2nd Round", "3rd Round", "4th Round", "Quarterfinalist", "Retired", "Semi-finalist", "Finalist", "Won")

tournament_scores <- timeline_processed %>% 
  filter(outcome %in% outcome_rakings) %>% 
  mutate(score_contribution = match(outcome, outcome_rakings)) %>% 
  group_by(player) %>% 
  mutate(previous_averange = lag(cummean(score_contribution), default = 1)) %>% 
  mutate(previous_performace = outcome_rakings[round(previous_averange)],
         previous_performace = fct_relevel(previous_performace, outcome_rakings))

```

```{r}
timeline_processed %>% 
  count(outcome, sort = TRUE) %>% 
  pull(outcome) %>% 
  dput()
```

```{r}
tournament_scores %>% 
  group_by(score_group = cut(previous_averange, seq(0,8), include.lowest = TRUE)) %>% 
  summarise(observations = n(),
            probability_win = mean(won)) %>% 
  ggplot(aes(
    score_group,
    probability_win,
    group = 1
  ))+
  geom_line()+
  scale_y_continuous(labels = scales::percent_format())+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(x = "Players average previous performance",
       y = "Probability of winning tournament",
       title = "Does pas performance in grand slams perdict future success?",
       subtitle = "Where 1st Round = 1, 2nd Round = 2... Finalist  = 7, Won = 8")
```
```{r}
tournament_scores %>% 
  group_by(previous_performace) %>% 
  summarise(observations = n(),
            probability_win = mean(won)) %>% 
  ggplot(aes(
    previous_performace,
    probability_win,
    group = 1
  ))+
  geom_line()+
  scale_y_continuous(labels = scales::percent_format())+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  labs(x = "Players average previous performance",
       y = "Probability of winning tournament",
       title = "Does pas performance in grand slams perdict future success?",
       subtitle = "Where 1st Round = 1, 2nd Round = 2... Finalist  = 7, Won = 8")
```
