---
title: "24_exercice"
author: "jorge_callejo"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = FALSE
)
library(tidyverse)
library(lubridate)
library(scales)
library(countrycode)
library(ggplot2)
library(plotly)
library(WDI)
library(janitor)
library(mapproj)
theme_set(theme_minimal())
```

```{r}
coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") %>% view()

mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") %>% view()

waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv") %>% view()
```



```{r}
clean_dataset <- function(tbl) {
  tbl %>%
    clean_names() %>%
    rename(country = entity,
           country_code = code) %>%
    filter(year == 2010) %>%
    select(-year)
}
plastic_waste <- coast_vs_waste %>%
  clean_dataset() %>%
  select(-total_population_gapminder) %>%
  inner_join(clean_dataset(mismanaged_vs_gdp) %>%
               select(-total_population_gapminder), by = c("country", "country_code")) %>%
  inner_join(clean_dataset(waste_vs_gdp), by = c("country", "country_code")) %>%
  select(country,
         country_code,
         mismanaged_waste = mismanaged_plastic_waste_tonnes,
         coastal_population,
         total_population = total_population_gapminder,
         mismanaged_per_capita = per_capita_mismanaged_plastic_waste_kilograms_per_person_per_day,
         gdp_per_capita = gdp_per_capita_ppp_constant_2011_international_rate) %>%
  filter(!is.na(mismanaged_waste))

```


```{r}
plastic_waste %>% 
  na.omit() %>% 
  filter(total_population >= 1e6) %>% 
  arrange(-total_population) %>% 
  ggplot(aes(
    gdp_per_capita,
    mismanaged_per_capita
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country_code), vjust = 1, hjust = -1, check_overlap = TRUE)+
  scale_x_log10( labels = scales:: dollar_format())+
  scale_y_log10()+
labs(x = "GDP per capita", 
     y = " Mismaraged plastic waste kg per day per person")+
  theme(legend.position = "bottom")
```
```{r}
plastic_waste %>% 
  na.omit() %>% 
  filter(total_population >= 1e6) %>% 
  arrange(-total_population) %>% 
  mutate(pct_pob_coastal = pmin(1, coastal_population / total_population), 
         high_coastal_pob = pct_pob_coastal >= 0.80) %>%
  ggplot( aes(
    gdp_per_capita,
    mismanaged_per_capita,
    color = high_coastal_pob
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = -1, check_overlap = TRUE)+
  scale_x_log10( labels = scales:: dollar_format())+
  scale_y_log10()+
labs(x = "GDP per capita", 
     y = " Mismaraged plastic waste kg per day per person",
     color = ">=80% pob")+
  theme(legend.position = "bottom")
```

```{r}
plastic_waste %>% 
  na.omit() %>% 
  arrange(-total_population) %>% 
  mutate(pct_pob_coastal = pmin(1, coastal_population / total_population), 
         high_coastal_pob = pct_pob_coastal >= 0.80) %>%
  ggplot( aes(
    gdp_per_capita,
    mismanaged_per_capita,
    color = high_coastal_pob
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = -1, check_overlap = TRUE)+
  scale_x_log10( labels = scales:: dollar_format())+
labs(x = "GDP per capita", 
     y = " Mismaraged plastic waste kg per day per person",
     color = ">=80% pob")+
  theme(legend.position = "bottom")
```

```{r}

plastic_waste %>% 
  na.omit() %>% 
  arrange(-total_population) %>% 
  mutate(pct_pob_coastal = pmin(1, coastal_population / total_population), 
         high_coastal_pob = ifelse(pct_pob_coastal >= 0.80, ">=80%", "<=80%")) %>%
  ggplot( aes(
    gdp_per_capita,
    mismanaged_per_capita,
    color = high_coastal_pob
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = -1, check_overlap = TRUE)+
  scale_x_log10( labels = scales:: dollar_format())+
labs(x = "GDP per capita", 
     y = " Mismaraged plastic waste kg per day per person",
     color = ">=80% pob",
     title = " How plastic waste mismangerent correlates with country income",
     subitle = "Based in our world in data 2010")+
  theme(legend.position = "bottom")
```


```{r}

g1 <- plastic_waste %>% 
  na.omit() %>% 
  arrange(-total_population) %>% 
  mutate(pct_pob_coastal = pmin(1, coastal_population / total_population), 
         high_coastal_pob = ifelse(pct_pob_coastal >= 0.80, ">=80%", "<=80%")) %>%
  ggplot( aes(
    gdp_per_capita,
    mismanaged_per_capita,
    color = high_coastal_pob
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = -1, check_overlap = TRUE)+
  scale_x_log10( labels = scales:: dollar_format())+
  scale_y_log10()+
  scale_size_continuous(guide = FALSE)+
labs(x = "GDP per capita", 
     y = " Mismaraged plastic waste kg per day per person",
     color = "Población costera",
     title = " How plastic waste mismangerent correlates with country income",
     subtitle = "Based in our world in data 2010")+
  theme(legend.position = "bottom")

g1
```


```{r}
maps::iso3166


plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3")) %>% 
  inner_join(map_data("world"), by = c("mapname" = "region"))
```
```{r}
maps::iso3166


plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3")) %>% 
  inner_join(map_data("world"), by = c("mapname" = "region")) %>% 
  ggplot(aes(
    long, 
    lat, 
    group = group
  ))+
  geom_polygon()
```
```{r}
maps::iso3166


plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3")) %>% 
  right_join(map_data("world"), by = c("mapname" = "region")) %>% 
  ggplot(aes(
    long, 
    lat, 
    group = group
  ))+
  geom_polygon()
```

```{r}
maps::iso3166


plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3")) %>% 
  right_join(map_data("world"), by = c("mapname" = "region")) %>% 
  ggplot(aes(
    long, 
    lat, 
    group = group,
    fill = mismanaged_per_capita
  ))+
  geom_polygon()
```
```{r}
maps::iso3166
library(fuzzyjoin)

plasstic_data <- plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3"))

map_data("world") %>% 
  tbl_df() %>% 
  regex_right_join(plasstic_data, c("region" = "mapname")) %>% 
  ggplot(aes(
    long,
    lat, 
    group = group,
    fill = mismanaged_per_capita
  ))+
  geom_polygon()+
  theme(legend.position = "bottom")
```
```{r}
maps::iso3166
library(fuzzyjoin)

plasstic_data <- plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3"))

map_data("world") %>% 
  tbl_df() %>% 
  filter(region != "Antarctica") %>% 
  regex_right_join(plasstic_data, c("region" = "mapname")) %>% 
  ggplot(aes(
    long,
    lat, 
    group = group,
    fill = mismanaged_per_capita
  ))+
  geom_polygon()+
  theme(legend.position = "bottom")+
  coord_map()
```
```{r}
maps::iso3166
library(fuzzyjoin)

plasstic_data <- plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3"))

map_data("world") %>% 
  tbl_df() %>% 
  filter(region != "Antarctica") %>% 
  regex_right_join(plasstic_data, c("region" = "mapname")) %>% 
  ggplot(aes(
    long,
    lat, 
    group = group,
    fill = mismanaged_per_capita
  ))+
  geom_polygon()+
  scale_fill_gradient2(trans = "log10",
                       low = "blue",
                       high = "red",
                       mid = "pink",
                       midpoint = log10(.02)) +
  theme(legend.position = "bottom")+
  coord_fixed(2)+
  ggthemes::theme_map()+
  labs(fill = "GDP")

```
```{r}
maps::iso3166
library(fuzzyjoin)

plasstic_data <- plastic_waste %>% 
  inner_join(maps::iso3166, by = c("country_code" = "a3"))

map_data("world") %>% 
  tbl_df() %>% 
  filter(region != "Antarctica") %>% 
  regex_right_join(plasstic_data, c("region" = "mapname")) %>% 
  ggplot(aes(
    long,
    lat, 
    group = group,
    fill = mismanaged_per_capita
  ))+
  geom_polygon()+
  theme(legend.position = "bottom")+
  scale_fill_continuous(trans = "log10")+
  coord_fixed(2)+
  ggthemes::theme_map()+
  labs(fill = "GDP")

```


```{r}
WDIsearch("emiss") %>% 
  view()

co2_emissions <- WDI(indicator = "EN.ATM.CO2E.PC", start = 2010, end = 2010) %>% 
  tbl_df() %>% 
  select(iso2c, co2_emissions_pp = EN.ATM.CO2E.PC) %>% 
  view()
```




```{r}
co2_emissions %>% 
  inner_join(plasstic_data, by = c(iso2c = "a2")) %>%
  arrange(desc(total_population)) %>% 
  ggplot(aes(
      gdp_per_capita,
      co2_emissions_pp
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = 1, check_overlap = TRUE)+
  scale_x_log10()+
  scale_y_log10()
  
```


```{r}
g2 <- co2_emissions %>% 
  inner_join(plasstic_data, by = c(iso2c = "a2")) %>%
  arrange(desc(total_population)) %>% 
  ggplot(aes(
      gdp_per_capita,
      co2_emissions_pp, 
      color = total_population
  ))+
  geom_point(aes(size = total_population))+
  geom_text(aes(label = country), vjust = 1, hjust = 1, check_overlap = TRUE)+
  scale_x_log10()+
  scale_y_log10()


g2
```


```{r}
#install.packages("patchwork")
library(patchwork)

g1 +
  labs(title = "CO2 emission are correlation with country income, but not plastic waste")+
  g2


```



